SELECT SIFRAZAP, IME, PREZIME, DATRODJ
FROM RADNIK
WHERE SIFRAODELJ = 10
FOR XML RAW;
GO

SELECT SIFRAZAP, IME, PREZIME, DATRODJ
FROM RADNIK
WHERE SIFRAODELJ = 10
FOR XML RAW, ELEMENTS;
GO

SELECT SIFRAZAP, IME, PREZIME, DATRODJ
FROM RADNIK
WHERE SIFRAODELJ = 10
FOR XML RAW, ELEMENTS, ROOT('Radnik');
GO


SELECT r.SIFRAZAP , r.IME, r.PREZIME, r.PREMIJA
FROM RADNIK r
FOR XML RAW;
GO


SELECT r.SIFRAZAP, r.IME, r.PREZIME, r.PREMIJA
FROM RADNIK r
FOR XML RAW('Radnik'),
ROOT('Radnici');
GO

SELECT r.SIFRAZAP, r.IME, r.PREZIME, r.PREMIJA
FROM RADNIK r
FOR XML RAW('Radnik'),
ROOT('Radnici'),
ELEMENTS XSINIL;
GO

SELECT SIFRAZAP, IME, PREZIME, PREMIJA
FROM RADNIK 
FOR XML AUTO,
ROOT('Radnici'),
ELEMENTS XSINIL;
GO

SELECT NAZIVODELJ, SIFRAZAP, IME, PREZIME, PREMIJA
FROM RADNIK, ODELJENJE
WHERE RADNIK.SIFRAODELJ = ODELJENJE.SIFRAODELJ
FOR XML AUTO,
ROOT('odeljenjaSaRdnicima'),
elements XSINIL;
GO