SELECT r.IME, r.PREZIME, r.SIFRAODELJ
FROM RADNIK r
WHERE r.SIFRAODELJ IN(SELECT SIFRAODELJ FROM 
RADNIK WHERE IME LIKE '_a%');


SELECT r.IME, r.PREZIME, r.SIFRAODELJ
FROM RADNIK r
WHERE r.SIFRAODELJ IN (SELECT SIFRAODELJ FROM RADNIK WHERE IME
LIKE '_a%')
AND IME NOT LIKE '_a%';


SELECT r.IME, r.PREZIME, r.SIFRAODELJ, r.PLATA
FROM RADNIK r
WHERE r.PLATA > (SELECT AVG(PLATA) FROM RADNIK);

SELECT r.IME, r.PREZIME, r.SIFRAODELJ, r.PLATA, (SELECT AVG(PLATA) AS prosecna_plata FROM RADNIK) AS prosek
FROM RADNIK r
WHERE r.PLATA > (SELECT AVG(PLATA) FROM RADNIK);


SELECT pod.IME, pod.PREZIME, pod.SIFRAODELJ, pod.PLATA
FROM RADNIK pod
WHERE pod.PLATA + 20000 >= (SELECT PLATA FROM RADNIK nad WHERE pod.SIFRARUKOV = nad.SIFRAZAP);

SELECT pod.IME, pod.PREZIME, pod.SIFRAODELJ, pod.PLATA, nad.PLATA as plata_nadredjenog
FROM RADNIK as pod,(SELECT PLATA,SIFRAZAP FROM RADNIK) as nad
WHERE pod.SIFRARUKOV = nad.SIFRAZAP AND pod.PLATA + 20000 >= nad.PLATA;

SELECT MIN(PLATA), AVG(PLATA), MAX(PLATA), COUNT(*), SIFRAODELJ
FROM RADNIK
WHERE SIFRAODELJ IS NOT NULL
GROUP BY SIFRAODELJ