SELECT r.IME, r.PREZIME, r.PREMIJA
FROM RADNIK r
WHERE r.PREMIJA IS NULL;

SELECT r.IME, r.PREZIME, r.PREMIJA
FROM RADNIK r
WHERE r.PREMIJA IS NOT NULL

SELECT r.IME, r.PLATA, r.PREMIJA, r.PLATA + ISNULL(0,r.PREMIJA) as "Ukupna primanja"
FROM RADNIK r
WHERE r.SIFRARUKOV IS NOT NULL

SELECT r.IME, r.PREZIME, ISNULL(r.SIFRAPROF,0) as "Obr. profil ili 0"
FROM RADNIK r

SELECT r.IME, r.PREZIME, r.PLATA,
(CASE WHEN PLATA < 40000 THEN 'Mala'
WHEN PLATA < 50000 THEN 'Srednja'
WHEN PLATA < 60000 THEN 'Dobra'
ELSE 'Odlicna'
END) as "Klasifikacija plata"
FROM RADNIK r


SELECT r.IME, r.PREZIME, r.SIFRAODELJ, r.PLATA,
(CASE SIFRAODELJ WHEN 10 THEN PLATA*1.05
WHEN 20 THEN PLATA*1.0
WHEN 30 THEN PLATA*1.15
WHEN 40 THEN PLATA*1.20
ELSE PLATA*1.25
END) as "Uvecna plata"
FROM RADNIK r


SELECT r.IME, r.PREZIME, r.SIFRAODELJ, r.PLATA
FROM RADNIK r
ORDER BY r.SIFRAODELJ ASC,r.PLATA DESC;

