
SELECT SIFRAODELJ, MIN(PLATA) AS MIN_PLATA
FROM RADNIK
GROUP BY SIFRAODELJ
HAVING MIN(PLATA) > (SELECT MIN(PLATA)
					FROM RADNIK
					WHERE SIFRAODELJ = 30);


SELECT SIFRAODELJ, MIN(PLATA) AS MIN_PLATA
FROM RADNIK
GROUP BY SIFRAODELJ
HAVING MIN(PLATA) > (SELECT MIN(PLATA)
					FROM RADNIK
					WHERE SIFRAODELJ = 30) AND SIFRAODELJ IS NOT NULL;


SELECT SIFRAODELJ, NAZIVODELJ, (SELECT SUM(PLATA) FROM RADNIK
WHERE SIFRAODELJ = ODELJENJE.SIFRAODELJ) as "Uk. plata radnika"
FROM ODELJENJE


SELECT r.IME, r.PREZIME, r.SIFRAPROF, r.PREMIJA
FROM RADNIK r
WHERE r.SIFRAODELJ != 30 AND r.PLATA > (
SELECT MAX(PLATA)
FROM RADNIK
WHERE SIFRAODELJ = 30)

SELECT pod.SIFRAZAP, pod.IME, pod.PREZIME, pod.SIFRAPROF, pod.SIFRARUKOV
FROM RADNIK pod
WHERE pod.SIFRAPROF != (SELECT nad.SIFRAPROF FROM RADNIK nad WHERE pod.SIFRARUKOV = nad.SIFRAZAP)

SELECT r.IME, r.PREZIME, o.NAZIVODELJ, o.GRAD
FROM RADNIK as r JOIN ODELJENJE as o ON
r.SIFRAODELJ = o.SIFRAODELJ

SELECT r.IME, r.PREZIME, rm.NAZIVRM, a.DATOD
FROM RADNO_MESTO as rm JOIN ANGAZOVANJE as a ON
rm.SIFRARM = a.SIFRARM JOIN RADNIK as r ON
r.SIFRAZAP = a.SIFRAZAP
AND a.DATDO IS NOT NULL

SELECT pod.IME, pod.PREZIME, pod.SIFRARUKOV, pod.PLATA, nad.IME as "nad_ime", nad.PREZIME as "nad_prezime"
FROM RADNIK as pod  JOIN RADNIK as nad ON
pod.SIFRARUKOV = nad.SIFRAZAP

SELECT pod.IME, pod.PREZIME, pod.SIFRARUKOV, pod.PLATA, nad.IME as "nad_ime", nad.PREZIME as "nad_prezime"
FROM RADNIK as pod LEFT JOIN RADNIK as nad ON
pod.SIFRARUKOV = nad.SIFRAZAP


SELECT r.IME, r.PREZIME, r.PLATA, ob.STEPENSTRUCNESPREME, ob.NAZIVPROF
FROM RADNIK as r  JOIN OBRAZOVNI_PROFIL as ob ON
r.SIFRAPROF = ob.SIFRAPROF
ORDER BY r.PLATA ASC;

SELECT r.IME, r.PREZIME, r.PLATA, ob.STEPENSTRUCNESPREME, ob.NAZIVPROF
FROM RADNIK as r LEFT JOIN OBRAZOVNI_PROFIL as ob ON
r.SIFRAPROF = ob.SIFRAPROF
ORDER BY r.PLATA ASC;

SELECT pod.IME, pod.PREZIME, pod.PLATA, pod.DATRODJ, nad.IME as "nad_ime", nad.PREZIME as "nad_prezime", nad.DATRODJ as "nad_datrodjenja"
FROM RADNIK as pod JOIN RADNIK as nad ON
pod.SIFRARUKOV = nad.SIFRAZAP
WHERE pod.DATRODJ < nad.DATRODJ

SELECT r.IME, r.PREZIME, rs.NAZIVRS, a.DATOD
FROM RADNIK as r JOIN ANGAZOVANJE as a ON
r.SIFRAZAP = a.SIFRAZAP JOIN RADNI_STATUS as rs ON
rs.SIFRARS = a.SIFRARS
AND a.DATDO IS NULL;